[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = ["-std=c++17", "-DLOCAL", "-Wall", "-Wextra", "-Wshadow", "-Wfloat-equal", "-Wno-sign-compare", "-g", "-fsanitize=undefined,address", "-fsplit-stack", "-D_GLIBCXX_DEBUG"]
